services:
  pgDB:
    image: postgres:latest
    container_name: pgDB
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Ashibhatt123@
      - POSTGRES_DB=DB
    volumes:
      - postgres_data:/var/lib/postgresql/data

  node-app:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: node-app
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:Ashibhatt123%40@pgDB:5432/DB
      - PORT=5000
    depends_on:
      - pgDB
    restart: always

  web:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "5173:5173"
    depends_on:
      - node-app
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
      - node-app

volumes:
  postgres_data:
